from typing import Any, Dict

from fastapi import APIRouter, Depends, HTTPException, Query, status
from sqlalchemy.orm import Session

from app.api.deps import get_current_user
from app.core.database import get_db
from app.crud import game as crud_game
from app.models.user import User
from app.schemas.game import Game, GameCreate

router = APIRouter()


@router.get("/search", response_model=Dict[str, Any])
async def search_games(
    query: str = Query(..., min_length=1, max_length=200, description="Search query"),
    page_size: int = Query(10, ge=1, le=40, description="Results per page"),
    page: int = Query(1, ge=1, description="Page number"),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> Dict[str, Any]:
    """
    Search games in local database (AI-generated games using Llama 3.1).
    
    - **query**: Search term (game name)
    - **page_size**: Results per page (1-40)
    - **page**: Page number (1-based)
    
    **Note:** Games are generated by Llama 3.1 8B Instruct based on book themes.
    To get new game recommendations, use POST /recommendations/
    """
    try:
        # Busca na base local
        skip = (page - 1) * page_size
        games = crud_game.search_games(db, query=query, skip=skip, limit=page_size)
        total_count = crud_game.count_games(db, query=query)
        
        return {
            "count": total_count,
            "results": [{
                "id": g.rawg_id,
                "name": g.name,
                "slug": g.slug,
                "rating": g.rating,
                "released": g.released,
                "background_image": g.image_url,
                "genres": g.genres,
                "tags": g.tags,
            } for g in games],
            "query": query,
            "page": page,
            "page_size": page_size,
        }
        
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Database error: {str(e)}",
        )


@router.get("/{game_id}", response_model=Game)
async def get_game_details(
    game_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> Game:
    """
    Get detailed information about a specific game by internal ID.
    
    - **game_id**: Internal game ID (integer)
    """
    game = crud_game.get_game(db, game_id)
    
    if not game:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Game with ID {game_id} not found in database",
        )
    
    return game


@router.get("/tags/{tags}", response_model=Dict[str, Any])
async def search_games_by_tags(
    tags: str,
    page_size: int = Query(10, ge=1, le=40, description="Results per page"),
    page: int = Query(1, ge=1, description="Page number"),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> Dict[str, Any]:
    """
    Search games by tags in local database (e.g., 'fantasy,magic,rpg').
    
    - **tags**: Comma-separated tags
    - **page_size**: Results per page (1-40)
    - **page**: Page number
    
    **Note:** Games generated by Llama 3.1 based on literary genres and themes.
    To get new recommendations, use POST /recommendations/
    """
    try:
        tag_list = [tag.strip() for tag in tags.split(",") if tag.strip()]
        
        if not tag_list:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="At least one tag is required",
            )
        
        if len(tag_list) > 10:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Maximum 10 tags allowed",
            )
        
        # Busca na base local por tags
        skip = (page - 1) * page_size
        games = crud_game.search_by_tags(db, tags=tag_list, skip=skip, limit=page_size)
        total_count = crud_game.count_by_tags(db, tags=tag_list)
        
        return {
            "count": total_count,
            "results": [{
                "id": g.rawg_id,
                "name": g.name,
                "slug": g.slug,
                "rating": g.rating,
                "released": g.released,
                "background_image": g.image_url,
                "genres": g.genres,
                "tags": g.tags,
            } for g in games],
            "tags": tag_list,
            "page": page,
            "page_size": page_size,
        }
        
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Database error: {str(e)}",
        )


@router.post("/", response_model=Game, status_code=status.HTTP_201_CREATED)
async def create_game(
    game_in: GameCreate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> Game:
    """
    Create a game in the local database.
    
    Used internally when saving recommendations.
    """
    existing_game = crud_game.get_game_by_rawg_id(db, game_in.rawg_id)
    
    if existing_game:
        return existing_game
    
    game = crud_game.create_game(db, game_in)
    return game
